### PR TITLE
Fix PostAndTryAsyncReply not to return null

### LINKED ISSUE #5: PostAndTryAsyncReply returns null
https://github.com/kthompson/Actress/blob/master/src/Actress/MailboxProcessor.cs#L120

here should be `return Task.FromResult<TReply>(default);`, otherwise awaiting this (`await PostAndTryAsyncReply`) could throw NullReferenceException

also there is strange difference in PostAndReply and PostAndAsyncReply. First contains:
```
 if (!Equals(res, default(TReply)))
     return res;
```

but second contains:

```
if (res != null)
     return res;
```

### PR DESCRIPTION
**Pull request by sm-g**
fixes #5

### CODE REVIEW

File: src/Actress/MailboxProcessor.cs [hunk 1]
```diff
@@ -117,17 +117,16 @@ public Task<TReply> PostAndTryAsyncReply<TReply>(Func<IReplyChannel<TReply>, TMs
...
-            int? timeout = null)
+        public async Task<TReply> PostAndAsyncReply<TReply>(Func<IReplyChannel<TReply>, TMsg> msgf, int? timeout = null)
         {
             var res = await PostAndTryAsyncReply(msgf, timeout);
-            if (res != null)
+            if (!Equals(res, default(TReply)))
                 return res;
 
-            throw new TimeoutException("MailboxProcessor PostAndReply timed out");
+            throw new TimeoutException($"MailboxProcessor PostAndAsyncReply timed out");
```
Comment (inosik) [inline src/Actress/MailboxProcessor.cs]:
```suggestion
            throw new TimeoutException("MailboxProcessor PostAndAsyncReply timed out");
```

**Review by inosik — CHANGES_REQUESTED** [review]

**Comment by inosik** [comment]
Thank you for fixing this!
